#!/bin/bash
set -e
echo "-----> Deploying nginx..."
APP="$1"; PORT="$2"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #this directory
APP_PATH="/home/git/$APP"
VHOST_PATH="$APP_PATH/VHOST"
SSL_DIR="$HOME/$APP/ssl"

# Check if a VHOST exists. If not, default to proxying the server's hostname
# (which may not always be correct, but worth a try).
if [[ ! -f $VHOST_PATH ]]; then
  echo "-----> Creating new $VHOST_PATH with hostname: $HOSTNAME..."
  echo "$HOSTNAME" > $VHOST_PATH
fi
# Get list of VHOST domains. This will be overridden below if SSL for some
# domains are enabled.
NONSSL_VHOSTS=`cat $VHOST_PATH`

# Remove old nginx.conf if exists
rm $APP_PATH/nginx.conf

# Add once-off configuration options. These should NOT go in the .conf
# templates because the .conf templates are meant to be appendable for multiple
# domains.
echo "upstream $APP { server 127.0.0.1:$PORT; }" > $APP_PATH/nginx.conf

# Check if SSL should be enabled
if [[ -f "$SSL_DIR/server.crt" ]] && [[ -f "$SSL_DIR/server.key" ]]; then
  NGINX_CONF="$DIR/nginx.ssl.conf" #default SSL conf file

  # Get the SSL certificate domain name and prepare it so that it satisfies
  # grep's regex syntax.
  # e.g. mydomain.com -> mydomain\.com
  #      *.mydomain.com -> .*\.mydomain\.com
  SSL_HOSTNAME=`openssl x509 -in $SSL_DIR/server.crt -noout -subject | tr '/' '\n' | grep CN= | cut -c4-`
  SSL_HOSTNAME=`echo "$SSL_HOSTNAME" | sed 's|\.|\\.|g' | sed 's/\*/\.\*/g'`

  # Only set up SSL for VHOST domains that the SSL certificate apply to. 
  # (If the SSL certificate is a wildcard subdomain, any VHOST domain that
  # satisfies the wildcard is included.)
  SSL_VHOSTS=`grep "$SSL_HOSTNAME" $VHOST_PATH`
  NONSSL_VHOSTS=`grep -v "$SSL_HOSTNAME" $VHOST_PATH` #-v flag means inverse

  # For each domain that satisfies the SSL certificate, set up nginx under the
  # SSL template.
  while read line; do
    echo "-----> Configuring SSL for $line..."
    SERVER_NAME=$line
    eval "cat <<< \"$(< $NGINX_CONF)\" >> $HOME/$APP/nginx.conf"
  done <<< "$SSL_VHOSTS"
fi

# Now handle non-SSL domains
NGINX_CONF="$DIR/nginx.conf" # default non-SSL conf file
# The VHOST file can contain more than one custom domain. We add each as a single
# line to the server_name parameter of nginx instead of creating separate 
# server_name entries for each.
cat $VHOST_PATH | xargs -i \
  echo "-----> Configuring {}..."
SERVER_NAME=`echo $NONSSL_VHOSTS | tr '\n' ' '`
eval "cat <<< \"$(< $NGINX_CONF)\" >> $HOME/$APP/nginx.conf"

pluginhook nginx-pre-reload $APP
echo '-----> Reloading nginx...'
nc -U $HOME/reload-nginx

cat #prints output from any plugins chained to this
